@KohTaoBack_HostAddress = http://localhost:5041

GET {{KohTaoBack_HostAddress}}/health

###

GET {{KohTaoBack_HostAddress}}/api/productos
Accept: application/json

###

# Debe devolver 401 sin sesión
GET {{KohTaoBack_HostAddress}}/api/encargos
Accept: application/json

###
